FROM python:3.11

WORKDIR /code

RUN apt update

#COPY src/b_fastapi/main.py /code
#COPY run.sh /code/run.sh

RUN pip install --no-cache-dir --upgrade https://github.com/DE32-3nd-team1/DE32-3nd-team1.git@fastapi

#CMD ["sh", "run.sh"]
